### ISSUE TITLE
WriteRaster TypeError: not a string

### ISSUE THREAD

**Issue by d33tah** [commenthol/gdal2tiles-leaflet#14]
```
ubuntu@ip-172-31-31-248:~$ python gdal2tiles-leaflet/gdal2tiles.py -z 0-11 -l -p raster -w none /mnt/1000/combined2.png /mnt/1000/out/
Generating Base Tiles:
0...10...20...30...40...50...60...70..ERROR 1: libpng: Read Error
ERROR 1: /mnt/1000/combined2.png, band 1: IReadBlock failed at X offset 0, Y offset 49257
Traceback (most recent call last):
  File "gdal2tiles-leaflet/gdal2tiles.py", line 2925, in <module>
    gdal2tiles.process()
  File "gdal2tiles-leaflet/gdal2tiles.py", line 606, in process
    self.generate_base_tiles()
  File "gdal2tiles-leaflet/gdal2tiles.py", line 1718, in generate_base_tiles
    + 1)),
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 2038, in WriteRaster
    buf_pixel_space, buf_line_space, buf_band_space )
TypeError: not a string
```

Not sure if this is reproducible yet as generating tiles takes ages:

```
/mnt/1000/combined2.png: PNG image data, 65536 x 65536, 8-bit/color RGB, non-interlaced
```

**Comment by superware** [comment]
@d33tah Have you resolved this?

**Comment by d33tah** [comment]
@superware I don't recall resolving it.
